-- Reverse of 2026-08-04-000036_tenant_keys.
--
-- Every foreign key goes back to naming its target by id alone, which is the
-- state in which a row could point at another tenant's. Nothing is lost that a
-- rebuild could not restore -- but the schema stops refusing the write, and that
-- is the whole of what this migration did.
--
-- Generated by inverting the up migration rather than typed, for the same reason
-- it was.

-- consignment_package leaves the tenancy boundary again.
DROP POLICY IF EXISTS consignment_package_tenant_scoped ON consignment_package;
ALTER TABLE consignment_package DISABLE ROW LEVEL SECURITY;
ALTER TABLE consignment_package
    DROP CONSTRAINT consignment_package_consignment_id_fkey,
    DROP CONSTRAINT consignment_package_package_id_fkey;
ALTER TABLE consignment_package
    ADD CONSTRAINT consignment_package_consignment_id_fkey
        FOREIGN KEY (consignment_id) REFERENCES consignment (id),
    ADD CONSTRAINT consignment_package_package_id_fkey
        FOREIGN KEY (package_id) REFERENCES package (id);
ALTER TABLE consignment_package DROP CONSTRAINT consignment_package_tenant_fk;
ALTER TABLE consignment_package DROP COLUMN tenant_id;
ALTER TABLE consignment DROP CONSTRAINT consignment_tenant_key;

-- 70 foreign keys, back to the tenant-blind form.

ALTER TABLE "assertion" DROP CONSTRAINT assertion_correction_of_assertion_id_fkey;
ALTER TABLE "assertion" ADD CONSTRAINT assertion_correction_of_assertion_id_fkey
    FOREIGN KEY (correction_of_assertion_id) REFERENCES "assertion" (id);
ALTER TABLE "assertion" DROP CONSTRAINT assertion_supersedes_assertion_id_fkey;
ALTER TABLE "assertion" ADD CONSTRAINT assertion_supersedes_assertion_id_fkey
    FOREIGN KEY (supersedes_assertion_id) REFERENCES "assertion" (id);

ALTER TABLE "discrepancy" DROP CONSTRAINT discrepancy_holder_location_id_fkey;
ALTER TABLE "discrepancy" ADD CONSTRAINT discrepancy_holder_location_id_fkey
    FOREIGN KEY (holder_location_id) REFERENCES "location" (id);
ALTER TABLE "discrepancy" DROP CONSTRAINT discrepancy_lot_id_fkey;
ALTER TABLE "discrepancy" ADD CONSTRAINT discrepancy_lot_id_fkey
    FOREIGN KEY (lot_id) REFERENCES "lot" (id);
ALTER TABLE "discrepancy" DROP CONSTRAINT discrepancy_holder_package_id_fkey;
ALTER TABLE "discrepancy" ADD CONSTRAINT discrepancy_holder_package_id_fkey
    FOREIGN KEY (holder_package_id) REFERENCES "package" (id);
ALTER TABLE "discrepancy" DROP CONSTRAINT discrepancy_package_event_id_fkey;
ALTER TABLE "discrepancy" ADD CONSTRAINT discrepancy_package_event_id_fkey
    FOREIGN KEY (package_event_id) REFERENCES "package_event" (id);
ALTER TABLE "discrepancy" DROP CONSTRAINT discrepancy_counterparty_party_id_fkey;
ALTER TABLE "discrepancy" ADD CONSTRAINT discrepancy_counterparty_party_id_fkey
    FOREIGN KEY (counterparty_party_id) REFERENCES "party" (id);
ALTER TABLE "discrepancy" DROP CONSTRAINT discrepancy_owner_id_fkey;
ALTER TABLE "discrepancy" ADD CONSTRAINT discrepancy_owner_id_fkey
    FOREIGN KEY (owner_id) REFERENCES "party" (id);
ALTER TABLE "discrepancy" DROP CONSTRAINT discrepancy_resolving_movement_id_fkey;
ALTER TABLE "discrepancy" ADD CONSTRAINT discrepancy_resolving_movement_id_fkey
    FOREIGN KEY (resolving_movement_id) REFERENCES "stock_movement" (id);
ALTER TABLE "discrepancy" DROP CONSTRAINT discrepancy_stock_movement_id_fkey;
ALTER TABLE "discrepancy" ADD CONSTRAINT discrepancy_stock_movement_id_fkey
    FOREIGN KEY (stock_movement_id) REFERENCES "stock_movement" (id);

ALTER TABLE "expected_supply" DROP CONSTRAINT expected_supply_owner_id_fkey;
ALTER TABLE "expected_supply" ADD CONSTRAINT expected_supply_owner_id_fkey
    FOREIGN KEY (owner_id) REFERENCES "party" (id);

ALTER TABLE "fulfilment" DROP CONSTRAINT fulfilment_order_id_fkey;
ALTER TABLE "fulfilment" ADD CONSTRAINT fulfilment_order_id_fkey
    FOREIGN KEY (order_id) REFERENCES "order" (id);

ALTER TABLE "fulfilment_line" DROP CONSTRAINT fulfilment_line_fulfilment_id_fkey;
ALTER TABLE "fulfilment_line" ADD CONSTRAINT fulfilment_line_fulfilment_id_fkey
    FOREIGN KEY (fulfilment_id) REFERENCES "fulfilment" (id);
ALTER TABLE "fulfilment_line" DROP CONSTRAINT fulfilment_line_order_line_id_fkey;
ALTER TABLE "fulfilment_line" ADD CONSTRAINT fulfilment_line_order_line_id_fkey
    FOREIGN KEY (order_line_id) REFERENCES "order_line" (id);

ALTER TABLE "intention_amendment" DROP CONSTRAINT intention_amendment_order_id_fkey;
ALTER TABLE "intention_amendment" ADD CONSTRAINT intention_amendment_order_id_fkey
    FOREIGN KEY (order_id) REFERENCES "order" (id);

ALTER TABLE "item_class" DROP CONSTRAINT item_class_parent_fk;
ALTER TABLE "item_class" ADD CONSTRAINT item_class_parent_fk
    FOREIGN KEY (parent_id) REFERENCES "item_class" (id);

ALTER TABLE "observable" DROP CONSTRAINT observable_item_packing_config_id_fkey;
ALTER TABLE "observable" ADD CONSTRAINT observable_item_packing_config_id_fkey
    FOREIGN KEY (item_packing_config_id) REFERENCES "item_packing_config" (id);
ALTER TABLE "observable" DROP CONSTRAINT observable_location_id_fkey;
ALTER TABLE "observable" ADD CONSTRAINT observable_location_id_fkey
    FOREIGN KEY (location_id) REFERENCES "location" (id);
ALTER TABLE "observable" DROP CONSTRAINT observable_lot_id_fkey;
ALTER TABLE "observable" ADD CONSTRAINT observable_lot_id_fkey
    FOREIGN KEY (lot_id) REFERENCES "lot" (id);
ALTER TABLE "observable" DROP CONSTRAINT observable_package_id_fkey;
ALTER TABLE "observable" ADD CONSTRAINT observable_package_id_fkey
    FOREIGN KEY (package_id) REFERENCES "package" (id);

ALTER TABLE "observation" DROP CONSTRAINT observation_corrects_observation_id_fkey;
ALTER TABLE "observation" ADD CONSTRAINT observation_corrects_observation_id_fkey
    FOREIGN KEY (corrects_observation_id) REFERENCES "observation" (id);
ALTER TABLE "observation" DROP CONSTRAINT observation_retracts_observation_id_fkey;
ALTER TABLE "observation" ADD CONSTRAINT observation_retracts_observation_id_fkey
    FOREIGN KEY (retracts_observation_id) REFERENCES "observation" (id);

ALTER TABLE "observation_event" DROP CONSTRAINT observation_event_observable_id_fkey;
ALTER TABLE "observation_event" ADD CONSTRAINT observation_event_observable_id_fkey
    FOREIGN KEY (observable_id) REFERENCES "observable" (id);
ALTER TABLE "observation_event" DROP CONSTRAINT observation_event_derived_from_event_id_fkey;
ALTER TABLE "observation_event" ADD CONSTRAINT observation_event_derived_from_event_id_fkey
    FOREIGN KEY (derived_from_event_id) REFERENCES "observation_event" (id);
ALTER TABLE "observation_event" DROP CONSTRAINT observation_event_asserted_by_party_id_fkey;
ALTER TABLE "observation_event" ADD CONSTRAINT observation_event_asserted_by_party_id_fkey
    FOREIGN KEY (asserted_by_party_id) REFERENCES "party" (id);

ALTER TABLE "order" DROP CONSTRAINT order_supersedes_order_id_fkey;
ALTER TABLE "order" ADD CONSTRAINT order_supersedes_order_id_fkey
    FOREIGN KEY (supersedes_order_id) REFERENCES "order" (id);
ALTER TABLE "order" DROP CONSTRAINT order_customer_party_id_fkey;
ALTER TABLE "order" ADD CONSTRAINT order_customer_party_id_fkey
    FOREIGN KEY (customer_party_id) REFERENCES "party" (id);

ALTER TABLE "order_line" DROP CONSTRAINT order_line_order_id_fkey;
ALTER TABLE "order_line" ADD CONSTRAINT order_line_order_id_fkey
    FOREIGN KEY (order_id) REFERENCES "order" (id);

ALTER TABLE "package" DROP CONSTRAINT package_fulfilment_id_fkey;
ALTER TABLE "package" ADD CONSTRAINT package_fulfilment_id_fkey
    FOREIGN KEY (fulfilment_id) REFERENCES "fulfilment" (id);
ALTER TABLE "package" DROP CONSTRAINT package_location_id_fkey;
ALTER TABLE "package" ADD CONSTRAINT package_location_id_fkey
    FOREIGN KEY (location_id) REFERENCES "location" (id);
ALTER TABLE "package" DROP CONSTRAINT package_resolved_location_id_fkey;
ALTER TABLE "package" ADD CONSTRAINT package_resolved_location_id_fkey
    FOREIGN KEY (resolved_location_id) REFERENCES "location" (id);
ALTER TABLE "package" DROP CONSTRAINT package_parent_package_id_fkey;
ALTER TABLE "package" ADD CONSTRAINT package_parent_package_id_fkey
    FOREIGN KEY (parent_package_id) REFERENCES "package" (id);
ALTER TABLE "package" DROP CONSTRAINT package_placement_event_id_fkey;
ALTER TABLE "package" ADD CONSTRAINT package_placement_event_id_fkey
    FOREIGN KEY (placement_event_id) REFERENCES "package_event" (id);

ALTER TABLE "package_containment" DROP CONSTRAINT package_containment_location_id_fkey;
ALTER TABLE "package_containment" ADD CONSTRAINT package_containment_location_id_fkey
    FOREIGN KEY (location_id) REFERENCES "location" (id);
ALTER TABLE "package_containment" DROP CONSTRAINT package_containment_package_id_fkey;
ALTER TABLE "package_containment" ADD CONSTRAINT package_containment_package_id_fkey
    FOREIGN KEY (package_id) REFERENCES "package" (id);
ALTER TABLE "package_containment" DROP CONSTRAINT package_containment_parent_package_id_fkey;
ALTER TABLE "package_containment" ADD CONSTRAINT package_containment_parent_package_id_fkey
    FOREIGN KEY (parent_package_id) REFERENCES "package" (id);
ALTER TABLE "package_containment" DROP CONSTRAINT package_containment_source_event_id_fkey;
ALTER TABLE "package_containment" ADD CONSTRAINT package_containment_source_event_id_fkey
    FOREIGN KEY (source_event_id) REFERENCES "package_event" (id);

ALTER TABLE "package_event" DROP CONSTRAINT package_event_location_id_fkey;
ALTER TABLE "package_event" ADD CONSTRAINT package_event_location_id_fkey
    FOREIGN KEY (location_id) REFERENCES "location" (id);
ALTER TABLE "package_event" DROP CONSTRAINT package_event_package_id_fkey;
ALTER TABLE "package_event" ADD CONSTRAINT package_event_package_id_fkey
    FOREIGN KEY (package_id) REFERENCES "package" (id);
ALTER TABLE "package_event" DROP CONSTRAINT package_event_parent_package_id_fkey;
ALTER TABLE "package_event" ADD CONSTRAINT package_event_parent_package_id_fkey
    FOREIGN KEY (parent_package_id) REFERENCES "package" (id);

ALTER TABLE "party_class" DROP CONSTRAINT party_class_parent_id_fkey;
ALTER TABLE "party_class" ADD CONSTRAINT party_class_parent_id_fkey
    FOREIGN KEY (parent_id) REFERENCES "party_class" (id);

ALTER TABLE "party_message" DROP CONSTRAINT party_message_acknowledges_party_message_id_fkey;
ALTER TABLE "party_message" ADD CONSTRAINT party_message_acknowledges_party_message_id_fkey
    FOREIGN KEY (acknowledges_party_message_id) REFERENCES "party_message" (id);

ALTER TABLE "policy_binding" DROP CONSTRAINT policy_binding_owner_party_id_fkey;
ALTER TABLE "policy_binding" ADD CONSTRAINT policy_binding_owner_party_id_fkey
    FOREIGN KEY (owner_party_id) REFERENCES "party" (id);
ALTER TABLE "policy_binding" DROP CONSTRAINT policy_binding_party_id_fkey;
ALTER TABLE "policy_binding" ADD CONSTRAINT policy_binding_party_id_fkey
    FOREIGN KEY (party_id) REFERENCES "party" (id);
ALTER TABLE "policy_binding" DROP CONSTRAINT policy_binding_site_id_fkey;
ALTER TABLE "policy_binding" ADD CONSTRAINT policy_binding_site_id_fkey
    FOREIGN KEY (site_id) REFERENCES "site" (id);
ALTER TABLE "policy_binding" DROP CONSTRAINT policy_binding_zone_id_fkey;
ALTER TABLE "policy_binding" ADD CONSTRAINT policy_binding_zone_id_fkey
    FOREIGN KEY (zone_id) REFERENCES "zone" (id);

ALTER TABLE "policy_change" DROP CONSTRAINT policy_change_item_class_id_fkey;
ALTER TABLE "policy_change" ADD CONSTRAINT policy_change_item_class_id_fkey
    FOREIGN KEY (item_class_id) REFERENCES "item_class" (id);
ALTER TABLE "policy_change" DROP CONSTRAINT policy_change_new_item_parent_id_fkey;
ALTER TABLE "policy_change" ADD CONSTRAINT policy_change_new_item_parent_id_fkey
    FOREIGN KEY (new_item_parent_id) REFERENCES "item_class" (id);
ALTER TABLE "policy_change" DROP CONSTRAINT policy_change_new_party_parent_id_fkey;
ALTER TABLE "policy_change" ADD CONSTRAINT policy_change_new_party_parent_id_fkey
    FOREIGN KEY (new_party_parent_id) REFERENCES "party_class" (id);
ALTER TABLE "policy_change" DROP CONSTRAINT policy_change_party_class_id_fkey;
ALTER TABLE "policy_change" ADD CONSTRAINT policy_change_party_class_id_fkey
    FOREIGN KEY (party_class_id) REFERENCES "party_class" (id);

ALTER TABLE "purchase_order" DROP CONSTRAINT purchase_order_supplier_party_id_fkey;
ALTER TABLE "purchase_order" ADD CONSTRAINT purchase_order_supplier_party_id_fkey
    FOREIGN KEY (supplier_party_id) REFERENCES "party" (id);

ALTER TABLE "purchase_order_line" DROP CONSTRAINT purchase_order_line_owner_party_id_fkey;
ALTER TABLE "purchase_order_line" ADD CONSTRAINT purchase_order_line_owner_party_id_fkey
    FOREIGN KEY (owner_party_id) REFERENCES "party" (id);

ALTER TABLE "stock" DROP CONSTRAINT stock_holder_location_id_fkey;
ALTER TABLE "stock" ADD CONSTRAINT stock_holder_location_id_fkey
    FOREIGN KEY (holder_location_id) REFERENCES "location" (id);
ALTER TABLE "stock" DROP CONSTRAINT stock_resolved_location_id_fkey;
ALTER TABLE "stock" ADD CONSTRAINT stock_resolved_location_id_fkey
    FOREIGN KEY (resolved_location_id) REFERENCES "location" (id);
ALTER TABLE "stock" DROP CONSTRAINT stock_lot_id_fkey;
ALTER TABLE "stock" ADD CONSTRAINT stock_lot_id_fkey
    FOREIGN KEY (lot_id) REFERENCES "lot" (id);
ALTER TABLE "stock" DROP CONSTRAINT stock_holder_package_id_fkey;
ALTER TABLE "stock" ADD CONSTRAINT stock_holder_package_id_fkey
    FOREIGN KEY (holder_package_id) REFERENCES "package" (id);
ALTER TABLE "stock" DROP CONSTRAINT stock_owner_id_fkey;
ALTER TABLE "stock" ADD CONSTRAINT stock_owner_id_fkey
    FOREIGN KEY (owner_id) REFERENCES "party" (id);

ALTER TABLE "stock_allocation" DROP CONSTRAINT stock_allocation_expected_supply_id_fkey;
ALTER TABLE "stock_allocation" ADD CONSTRAINT stock_allocation_expected_supply_id_fkey
    FOREIGN KEY (expected_supply_id) REFERENCES "expected_supply" (id) ON DELETE RESTRICT;
ALTER TABLE "stock_allocation" DROP CONSTRAINT stock_allocation_origin_expected_supply_id_fkey;
ALTER TABLE "stock_allocation" ADD CONSTRAINT stock_allocation_origin_expected_supply_id_fkey
    FOREIGN KEY (origin_expected_supply_id) REFERENCES "expected_supply" (id);
ALTER TABLE "stock_allocation" DROP CONSTRAINT stock_allocation_fulfilment_line_id_fkey;
ALTER TABLE "stock_allocation" ADD CONSTRAINT stock_allocation_fulfilment_line_id_fkey
    FOREIGN KEY (fulfilment_line_id) REFERENCES "fulfilment_line" (id);
ALTER TABLE "stock_allocation" DROP CONSTRAINT stock_allocation_stock_id_fkey;
ALTER TABLE "stock_allocation" ADD CONSTRAINT stock_allocation_stock_id_fkey
    FOREIGN KEY (stock_id) REFERENCES "stock" (id) ON DELETE RESTRICT;

ALTER TABLE "stock_movement" DROP CONSTRAINT stock_movement_from_location_id_fkey;
ALTER TABLE "stock_movement" ADD CONSTRAINT stock_movement_from_location_id_fkey
    FOREIGN KEY (from_location_id) REFERENCES "location" (id);
ALTER TABLE "stock_movement" DROP CONSTRAINT stock_movement_to_location_id_fkey;
ALTER TABLE "stock_movement" ADD CONSTRAINT stock_movement_to_location_id_fkey
    FOREIGN KEY (to_location_id) REFERENCES "location" (id);
ALTER TABLE "stock_movement" DROP CONSTRAINT stock_movement_from_lot_id_fkey;
ALTER TABLE "stock_movement" ADD CONSTRAINT stock_movement_from_lot_id_fkey
    FOREIGN KEY (from_lot_id) REFERENCES "lot" (id);
ALTER TABLE "stock_movement" DROP CONSTRAINT stock_movement_to_lot_id_fkey;
ALTER TABLE "stock_movement" ADD CONSTRAINT stock_movement_to_lot_id_fkey
    FOREIGN KEY (to_lot_id) REFERENCES "lot" (id);
ALTER TABLE "stock_movement" DROP CONSTRAINT stock_movement_from_package_id_fkey;
ALTER TABLE "stock_movement" ADD CONSTRAINT stock_movement_from_package_id_fkey
    FOREIGN KEY (from_package_id) REFERENCES "package" (id);
ALTER TABLE "stock_movement" DROP CONSTRAINT stock_movement_to_package_id_fkey;
ALTER TABLE "stock_movement" ADD CONSTRAINT stock_movement_to_package_id_fkey
    FOREIGN KEY (to_package_id) REFERENCES "package" (id);
ALTER TABLE "stock_movement" DROP CONSTRAINT stock_movement_from_owner_id_fkey;
ALTER TABLE "stock_movement" ADD CONSTRAINT stock_movement_from_owner_id_fkey
    FOREIGN KEY (from_owner_id) REFERENCES "party" (id);
ALTER TABLE "stock_movement" DROP CONSTRAINT stock_movement_to_owner_id_fkey;
ALTER TABLE "stock_movement" ADD CONSTRAINT stock_movement_to_owner_id_fkey
    FOREIGN KEY (to_owner_id) REFERENCES "party" (id);
ALTER TABLE "stock_movement" DROP CONSTRAINT stock_movement_reverses_movement_id_fkey;
ALTER TABLE "stock_movement" ADD CONSTRAINT stock_movement_reverses_movement_id_fkey
    FOREIGN KEY (reverses_movement_id) REFERENCES "stock_movement" (id);

-- And the keys that made carrying the tenant possible.
ALTER TABLE "fulfilment" DROP CONSTRAINT fulfilment_tenant_key;
ALTER TABLE "fulfilment_line" DROP CONSTRAINT fulfilment_line_tenant_key;
ALTER TABLE "location" DROP CONSTRAINT location_tenant_key;
ALTER TABLE "order" DROP CONSTRAINT order_tenant_key;
ALTER TABLE "order_line" DROP CONSTRAINT order_line_tenant_key;
ALTER TABLE "package_event" DROP CONSTRAINT package_event_tenant_key;
ALTER TABLE "stock" DROP CONSTRAINT stock_tenant_key;
ALTER TABLE "stock_movement" DROP CONSTRAINT stock_movement_tenant_key;
ALTER TABLE "zone" DROP CONSTRAINT zone_tenant_key;
