-- Migration 77 up: the projection owner and the scheduler may use the schema
-- they were built to work in.
--
-- Migration 3 creates both roles and grants them neither. Migration 1 grants
-- USAGE to nylonite_app and nylonite_platform, migration 48 to
-- nylonite_mediation_owner, and these two were never added to either list —
-- so on a cluster where they have only ever existed as these migrations made
-- them, they cannot see a single table.
--
-- **Seventeen SECURITY DEFINER functions are owned by nylonite_projection_owner**
-- — every projection maintainer, plus record_finding — and a definer function
-- runs as its owner. Without USAGE the whole schema is invisible to it, and
-- PostgreSQL reports that as `relation "projection_step" does not exist`
-- rather than as a permission error, which points the reader at a missing
-- table that is sitting right there.
--
-- nylonite_scheduler is the same defect with a different symptom: D107's drain
-- connects and SET ROLEs to it, and on a fresh deployment it would find
-- nothing to drain because it can see nothing at all.
--
-- **Why nobody noticed.** `scripts/verify-migrations.sh` granted exactly this,
-- to exactly these two roles, in its reset step — so every run repaired the
-- schema before testing it. Roles are cluster-wide, so any machine that had
-- ever run the script kept the grant forever, across every database on it. The
-- first cluster to see the truth was CI's, which is new every time. That grant
-- is removed from the script in the same commit as this migration: a fixture
-- that repairs what it is checking is worse than no fixture.

GRANT USAGE ON SCHEMA public TO nylonite_projection_owner, nylonite_scheduler;
